from ArgTest import ArgumentationFramework


af = ArgumentationFramework('test')
af.add_argument('a1')
af.add_argument('a11')
af.add_argument('a2')
af.add_argument('a10')
af.add_argument('a3')
af.add_argument('a4')
af.add_argument('a12')
af.add_argument('a5')
af.add_argument('a6')
af.add_argument('a7')
af.add_argument('a8')
af.add_argument('a9')

af.add_attack('a1', 'a3')
af.add_attack('a8', 'a12')
af.add_attack('a6', 'a4')
af.add_attack('a1', 'a9')
af.add_attack('a9', 'a11')
af.add_attack('a12', 'a6')
af.add_attack('a2', 'a5')
af.add_attack('a7', 'a8')
af.add_attack('a7', 'a9')
af.add_attack('a11', 'a3')
af.add_attack('a6', 'a12')
af.add_attack('a11', 'a9')
af.add_attack('a9', 'a1')
af.add_attack('a10', 'a4')
af.add_attack('a10', 'a2')
af.add_attack('a5', 'a2')
af.add_attack('a9', 'a7')
af.add_attack('a3', 'a11')


# print(af)
print(af.get_stable_extension())